### ISSUE TITLE
Combo box allows setting an empty value if it already has focus

### ISSUE THREAD

**Issue by eriklumme** [vaadin/vaadin-combo-box#501] opened 2017-08-22 07:25 UTC
### Description
When clearing an already focused `vaadin-combo-box`, the value is set to an empty string. If the element is not already focused, it will revert to its old value.

### Expected outcome
The element always reverts to the old value.

### Actual outcome
The value is set to an empty string.

### Steps to reproduce

1. Add a vaadin-combo-box with a few items.

<vaadin-combo-box items='["One", "Two", "Three", "Four"]'>
</vaadin-combo-box>

2. Select an item. Click outside the box so that it loses focus. Select all of the text in the box, delete it, and press enter. The combo box reverts to the last selection.

3. Click inside the box so that it has focus. Select all of the text in the box, delete it, and press enter.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by eriklumme** [comment] 2017-08-22 07:25
Not sure if this is intended. It works the same if instead of enter after deleting the text, you simply click outside the box. Esc always reverts to the last selection.

**Comment by jouni** [comment] 2017-10-04 10:12
I believe this is a duplicate of #522 

@eriklumme, could you test again with 3.0.0-alpha6 and see if you can still reproduce the issue.

**Comment by tomivirkki** [comment] 2018-05-16 11:53
Seems to be working fine with the latest version. Closing.

**Closed by tomivirkki** 2018-05-16 11:53 UTC
