### ISSUE TITLE
Dropdown list open speed regression

### ISSUE THREAD

**Issue by Waynezhi** [vaadin/vaadin-combo-box#605] opened 2018-01-25 16:02 UTC
### Description
Hello there,
i upgrade from very old version 1.0 to v3.0.2, in order to support polymer 2, but i got performance regression: for 500 elements in combobox, it displayed dropdown list immediately, but with the v3.0.2, it takes 2 or 3 seconds.
or just wait the new v4.0 ?

another question, the new combobox increased its height, any idea to reuse old v1.0 like (paper-input like) style ?

### Expected outcome
drop down list should open quickly

### Actual outcome
now it takes 3s to show 500 elements

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [X] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by jouni** [comment] 2018-01-26 07:25
> the new combobox increased its height, any idea to reuse old v1.0 like (paper-input like) style ?

v3 onwards we no longer use paper-input internally, but use vaadin-text-field instead. In v3, there’s a simple default theme, and in v4 we apply the Lumo theme as the default. You can use the vaadin-material-theme for both versions to get a material design input field: https://cdn.vaadin.com/vaadin-material-theme/0.3.0/demo/text-fields.html

We are currently working on an update to the material theme, which brings the combo box theme as well: https://github.com/vaadin/vaadin-material-theme/pull/17

**Comment by jouni** [comment] 2018-01-26 07:27
Apparently you already found the previous issue: https://github.com/vaadin/vaadin-combo-box/issues/526

Make sure you are not by any chance getting the vaadin-themable-mixin v1.2

**Comment by web-padawan** [comment] 2018-01-26 07:45
This is not caused by the themable-mixin. It looks like `iron-list` renders all nodes for some reason, instead of reusing. I was unable to quickly understand when it was introduced but this is still valid issue. My guess is that `max-height` does not work as expected.

**Comment by web-padawan** [comment] 2018-01-26 11:49
@Waynezhi thank you for reporting! This issue is now fixed on master branch. We will hopefully backport the fix to the `3.x` branch as well to cut the patch release soon.

**Comment by flyweight** [comment] 2018-02-07 01:38
@web-padawan What's the timing on getting this merged into 3.x?  Thanks 👍

**Comment by web-padawan** [comment] 2018-02-08 13:13
This appears to be also related to the timings that we have changed in vaadin/vaadin-overlay@58de6f5 so the fix is not enough (although still needed). I investigate what else should we do in order to fix this for `3.x`

**Closed** 2018-02-09 07:22 UTC
Labels: bug, in review

**Comment by web-padawan** [comment] 2018-02-09 07:28
@Waynezhi the issue is now fixed for `3.x` branch as well and released as `v3.0.3`. Please upgrade to that version, there should be no performance impact now.

About the second question:

> another question, the new combobox increased its height

If you mean the overlay height, there is a custom CSS property `--vaadin-combo-box-overlay-max-height` which you can use to configure it. The default values is `65vh`.

**Comment by Waynezhi** [comment] 2018-02-12 22:26
@web-padawan cool, that works like a charm.
about the height, i was talking about the padding-top of vaadin-text-field
bacause i have paper-checkbox and vaadin-combobox in the same line, but they have not the same height.
