### ISSUE TITLE
Pressing ESC when overlay is open clears the selected item (but not the value)

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-combo-box#622] opened 2018-03-05 12:34 UTC
### Description
Combo box can go into an inconsistent state when pressing the Esc key while the overlay is open and has an item selected.

### Expected outcome
The overlay is closed and selected item and value stay untouched.

### Actual outcome
The overlay is left open and the selected item checkmark is removed but the field value stays the same.

### Screen recording
![combo-box-bug](https://user-images.githubusercontent.com/66382/36975163-ee1aa5ca-2081-11e8-97b4-bd31550f45ce.gif)

### Steps to reproduce

1. Select an item from the overlay
2. Re-open the overlay
3. Press ESC

-> The `selectedItem` is `null` and `value` is still the selected value string.

**Comment by jouni** [comment] 2018-03-05 12:34
This seems like a regression from v3 – it didn’t seem to be reproducible with it.

**Comment by platosha** [comment] 2018-03-05 12:47
Cannot reproduce on this page for some reason: https://cdn.vaadin.com/vaadin-combo-box/4.0.0-beta3/demo/#combo-box-objects-demos

**Comment by jouni** [comment] 2018-03-05 12:57
True, I can’t reproduce it there either 🤔 

I was again using the Lumo styles kitchen sink example: https://github.com/vaadin/vaadin-lumo-styles/blob/master/test/sink.html

**Comment by web-padawan** [comment] 2018-03-05 13:49
The "Allow Custom Values" demo actually prevents the `custom-value-set` event: https://github.com/vaadin/vaadin-combo-box/blob/master/demo/combo-box-basic-demos.html#L127

If we didn't do that in demos, the issue would be reproducible there as well.

**Comment by web-padawan** [comment] 2018-09-24 12:37
@jouni could you clarify what behavior is expected? Do I understand correctly that:

1. pressing <kbd>Esc</kbd>  once should restore value to the previously selected one, if any
2. pressing <kbd>Esc</kbd>  twice should close the combo-box

Or, is <kbd>Esc</kbd> expected to also clear the value ?

**Comment by jouni** [comment] 2018-09-25 10:52
Sorry for the delay.

The desired behavior has been so that The first Esc key press reverts the value (or clears if the value is empty), and the second Esc key press closes the dropdown.

But I’ve been wanting to revisit that decision, and rather combine those two key presses into one. So pressing Esc should close the dropdown and revert value.

I think that should be an okay change at least in a minor version (not require a major), and should not disrupt existing users workflows too much.

**Comment by web-padawan** [comment] 2018-09-25 10:57
Thanks for the info. This is worth having another ticket so I will extract it from here.
Meanwhile the fix will be landed in #724 but I would be glad to have one Esc here.

**Comment by jouni** [comment] 2018-09-25 11:01
Would be helpful if the component behaviors were properly documented. It’s funny how it feels both useful and wasteful at the same time – you shouldn’t really produce documentation for documentation’s sake, but then again it would be helpful to avoid accidental/unwanted behavioral changes.

**Comment by jouni** [comment] 2018-09-25 11:05
I did create this a year ago, which does contain most of the behavior (the current one with two Esc key presses): 
![combo box state transitions](https://user-images.githubusercontent.com/66382/46010604-fbc9ca80-c0cb-11e8-94ca-5e4a70324f45.png)

**Closed** 2018-09-25 15:21 UTC
Labels: in review
