### ISSUE TITLE
Support autocomplete

### ISSUE THREAD

**Issue by sashamihaha** [vaadin/vaadin-combo-box#862] opened 2020-02-20 11:44 UTC
Currently, `<vaadin-combo-box>` doesn't support `autocomplete` attribute. The suggested workaround was to use `<vaadin-combo-box-light>` with slotted `<vaadin-text-field>` but I couldn't make it work with `autocomplete` either.

**Comment by web-padawan** [comment] 2020-03-31 13:46
`autocomplete` has been disabled intentionally by https://github.com/vaadin/vaadin-combo-box/commit/add0285b3d1c4563aa4499b723a40e13d3213c84 as part of #19

We could enable propagating it to `vaadin-text-field` which  [supports it](https://github.com/vaadin/vaadin-text-field/blob/1b9de983eca78db6d97e8d83ea8277af821ac248/src/vaadin-text-field-mixin.html#L138-L145).

**Comment by sashamihaha** [comment] 2020-04-01 07:37
That would be great.

**Comment by tomivirkki** [comment] 2020-04-01 07:55
I think it was originally disabled to not have the autocomplete dropdown appear (on top of combo-box's own dropdown):

<img width="215" alt="Screenshot 2020-04-01 10 52 34" src="https://user-images.githubusercontent.com/1222264/78112568-11c5f300-7407-11ea-81e1-0b4ace555ffd.png">

**Comment by web-padawan** [comment] 2020-10-15 11:22
Closing per above comment as working as intended.

**Closed by web-padawan** 2020-10-15 11:22 UTC
Labels: needs discussion
