### ISSUE TITLE
Iron Form issue doesn't validate required fields (Safari)

### ISSUE THREAD

**Issue by scmurdock** [vaadin/vaadin-combo-box#225] opened 2016-04-19 16:31 UTC
Hello, I just called Markus and he advised me to create an issue to track this. See example below (hit submit and see validation at work on Firefox/Chrome, but not Safari):

http://codepen.io/anon/pen/zqaNKd

Thanks guys!

Sean

**Comment by Saulis** [comment] 2016-04-20 06:20
Hi and thanks for the report!

After a quick test, looks like the problem might in be `<iron-form>`, since the same behaviour happens also just with a plain `<paper-input required>` placed inside a form. I'll try to see if I can find the root cause for the issue.

**Comment by Saulis** [comment] 2016-04-20 07:26
Looks like there is a conflict inside `<iron-form>` which occurs when you have an element named `submit` inside the form.

Created an issue to `<iron-form>`: https://github.com/PolymerElements/iron-form/issues/122

So as a workaround, you need to `name` the input something else than "submit". 

I'll close this issue since there isn't anything more we can do, but feel free to reopen if there's something still to be done. 

Thanks!

**Closed by Saulis** 2016-04-20 07:26 UTC
Labels: in progress
