### ISSUE TITLE
Uncaught TypeError: Cannot read property 'offsetHeight' of null

### ISSUE THREAD

**Issue by marksmits** [vaadin/vaadin-combo-box#222] opened 2016-04-15 13:25 UTC
When dynamically adding vaadin-combo-box element to the dom it gives this error in the console. This only happens if the value is set to the first element of the list.

var n = document.createElement('div');
n.innerHTML = '<vaadin-combo-box name="name" items=\'["test1","test2"]\' value="test1" required label="Element"></vaadin-combo-box>';

var elem = document.getElementById("testcontainer");
elem.appendChild(n); 

<div id="testcontainer"></div>
-----
VM820 iron-list.html:944 Uncaught TypeError: Cannot read property 'offsetHeight' of nullPolymer._updateMetrics @ VM820 iron-list.html:944Polymer.scrollToIndex @ VM820 iron-list.html:1019Polymer._scrollIntoView @ VM822 vaadin-combo-box-overlay.html:215Polymer._focusedIndexChanged @ VM822 vaadin-combo-box-overlay.html:209Polymer.Base.extend._observerEffect @ VM808 polymer.html:1563Polymer.Bind._modelApi._effectEffects @ VM808 polymer.html:1402Polymer.Bind._modelApi._propertySetter @ VM808 polymer.html:1386Polymer.Bind._modelApi.__setProperty @ VM808 polymer.html:1395Polymer.Base._addFeature._applyEffectValue @ VM808 polymer.html:1894Polymer.Base.extend._annotationEffect @ VM808 polymer.html:1546Polymer.Bind._modelApi._effectEffects @ VM808 polymer.html:1402Polymer.Bind._modelApi._propertySetter @ VM808 polymer.html:1386setter @ VM808 polymer.html:1465Polymer._selectedItemChanged @ VM824 vaadin-combo-box.html:593handler @ VM808 polymer.html:516Polymer.Base._addFeature.fire @ VM808 polymer.html:1272Polymer.Bind._modelApi._notifyChange @ VM808 polymer.html:1369Polymer.Base.extend._notifyEffect @ VM808 polymer.html:1554Polymer.Bind._modelApi._effectEffects @ VM808 polymer.html:1402Polymer.Bind._modelApi._propertySetter @ VM808 polymer.html:1386setter @ VM808 polymer.html:1465(anonymous function) @ VM808 polymer.html:1510Polymer.Base._addFeature._notifyListener @ VM808 polymer.html:2016(anonymous function) @ VM808 polymer.html:1531Polymer.Base._addFeature.fire @ VM808 polymer.html:1272Polymer.Bind._modelApi._notifyChange @ VM808 polymer.html:1369Polymer.Base.extend._notifyEffect @ VM808 polymer.html:1554Polymer.Bind._modelApi._effectEffects @ VM808 polymer.html:1402Polymer.Bind._modelApi._propertySetter @ VM808 polymer.html:1386setter @ VM808 polymer.html:1465(anonymous function) @ VM808 polymer.html:1510Polymer.Base._addFeature._notifyListener @ VM808 polymer.html:2016(anonymous function) @ VM808 polymer.html:1531Polymer.Base._addFeature.fire @ VM808 polymer.html:1272Polymer.Bind._modelApi._notifyChange @ VM808 polymer.html:1369Polymer.Base.extend._notifyEffect @ VM808 polymer.html:1554Polymer.Bind._modelApi._effectEffects @ VM808 polymer.html:1402Polymer.Bind._modelApi._propertySetter @ VM808 polymer.html:1386setter @ VM808 polymer.html:1465Polymer.select @ VM808 polymer.html:4626Polymer.selectItem @ VM820 iron-list.html:1114Polymer._selectItem @ VM822 vaadin-combo-box-overlay.html:263Polymer._setItems @ VM824 vaadin-combo-box.html:569Polymer.Base.extend._observerEffect @ VM808 polymer.html:1563Polymer.Bind._modelApi._effectEffects @ VM808 polymer.html:1402Polymer.Bind._modelApi._propertySetter @ VM808 polymer.html:1386Polymer.Bind._modelApi.__setProperty @ VM808 polymer.html:1395Polymer.Base._addFeature._applyConfig @ VM808 polymer.html:1997Polymer.Base._addFeature._afterClientsReady @ VM808 polymer.html:1991Polymer.Base._addFeature._ready @ VM807 polymer-mini.html:75Polymer.Base._addFeature._tryReady @ VM807 polymer-mini.html:61Polymer.Base._addFeature._initFeatures @ VM808 polymer.html:3576Polymer.Base.createdCallback @ VM806 polymer-micro.html:194(anonymous function) @ VM826 pen.js:2

**Comment by platosha** [comment] 2016-04-15 13:35
Hi! Thanks for reporting. Probably it's a duplicate of #182.

What version of vaadin-combo-box are you using? We might have fixed it in master already, a few days ago. Is there the same error in master for you?

**Comment by marksmits** [comment] 2016-04-15 13:49
I think it is the same issue but in my case i have a different reproduction. Please note that you will only get the error if you select the first element of the list. In my case test1 

Error:
`n.innerHTML = '<vaadin-combo-box name="name" items=\'["test1","test2"]\' value="test1" required label="Element"></vaadin-combo-box>';`

Good:
`n.innerHTML = '<vaadin-combo-box name="name" items=\'["test1","test2"]\' value="test2" required label="Element"></vaadin-combo-box>';`

Version:
    "vaadin-combo-box": "^1.0.0-beta1",

**Comment by Saulis** [comment] 2016-07-27 12:29
@marksmits are you still having this issue?

**Comment by marksmits** [comment] 2016-07-27 14:57
No this issue was solved when i switched to the 1.0.0 version

Thanks,
Mark

**Closed** 2016-07-28 07:12 UTC
