### ISSUE TITLE
Input value bottom gets cut off in IE11

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-combo-box#130] opened 2016-02-04 10:40 UTC
For values with letters like `y`, the bottom half gets cut off. Seems to happen only on IE11 (tested on Windows 7)

![image](https://cloud.githubusercontent.com/assets/1039468/12812732/6d49f9ec-cb3c-11e5-9bb1-8820f616c236.png)

**Comment by Saulis** [comment] 2016-02-08 10:02
Reopening this because of regression causing #91 to reapper.

**Comment by jounik** [comment] 2016-02-19 09:19
Here’s the relevant IE11 bug for paper-input: https://github.com/PolymerElements/paper-input/issues/171

Not a bug in our element per se, so I think we should revert the fix.

**Comment by samiheikki** [comment] 2016-10-27 12:43
Update: Tested on IE11. The y value doesn't get cut off anymore, but https://github.com/PolymerElements/paper-input/issues/171 is still an issue.

**Comment by tomivirkki** [comment] 2018-05-14 10:14
No longer relevant. Closing.

**Closed by tomivirkki** 2018-05-14 10:14 UTC
