### ISSUE TITLE
Always selects the first item in the list

### ISSUE THREAD

**Issue by PSVapour** [vaadin/vaadin-combo-box#310] opened 2016-09-16 15:43 UTC
If **item-label-path** is defined without an **item-value-path** the first item in the list is always selected on the initial item select. You have to then go into the drop again and select the item again.

**Comment by samiheikki** [comment] 2016-09-19 05:17
Hi!

I created a Plunker example based on your issue and seems to be working properly:
https://plnkr.co/edit/5Wx63BUg8n8CCkdOlJff?p=preview

I'm closing this issue now, but feel free to re-open it if you have an example where the combo-box is not working as it should. Thanks!

**Comment by tehapo** [comment] 2016-09-19 07:37
The default for `item-value-path` is `value` which is why your Plunker works. If you use something other than `value` property in your objects, you can reproduce the problem.

Not sure if this is a real bug though. I think you should always provide the `item-value-path` when it is something other than `value`.

**Comment by samiheikki** [comment] 2016-09-20 11:20
Yeah, not sure either is it a valid bug. `item-value-path` and `item-label-path` are meant to be used together and not without each other. @PSVapour could you provide us with a use case for setting only `item-label-path`?

**Comment by dengelke** [comment] 2016-10-06 10:09
Same problem however this is caused by having two elements with the same value parameter, see example https://embed.plnkr.co/g5upa8Mp2GFHhxei0nBy/ when 'name3' is clicked on 'name1' is selected, however the combo-box behaves normally when name1 or name2 is selected

**Comment by Saulis** [comment] 2016-12-19 15:54
@dengelke `v1.2.0-alpha1` has some improvements on this, I think it fixes your issue.

**Comment by dengelke** [comment] 2016-12-20 06:08
Thanks @Saulis, fixes my issue - any idea on when the 1.2.0 release will be out?

**Comment by Saulis** [comment] 2016-12-22 09:53
@dengelke we're aiming to get it out at the end of this year unless we bump to any surprises.

**Comment by platosha** [comment] 2017-05-26 12:33
Closing, the fix was released in v1.2.0 a while ago.

**Closed by platosha** 2017-05-26 12:33 UTC
