### ISSUE TITLE
Not working on each using vulcanize

### ISSUE THREAD

**Issue by dpinart** [vaadin/vaadin-combo-box#255] opened 2016-06-13 14:30 UTC
Hi

I've added this control wihtin the vulcanize process. It's working fine on most of broswers except on edge

**Comment by jouni** [comment] 2016-06-13 18:45
Hi, thanks for the report! What happens on edge?

**Comment by dpinart** [comment] 2016-06-14 08:19
Hi @jouni 
It's a weird issue. I have a login page with a vaadin-combo-box that  allows user to pick the target environment. On edge, the login page simply does not load. I can't see any explicit error message. It's working fine on chrome, fierefox and safari.
The app is a bit complex one, we use aurelia as the MVVM framework and polymer as the widgets library. We vulcanize all polymer widgets.

If we exclude vaadin-combobox from the vulcanize process we get an error and we try to import the widget

**Comment by platosha** [comment] 2016-06-20 11:37
Hi,

I can not reproduce this issue. Tried with a simple HTML page with only vaadin-combo-box used. Still works in Edge for me after vulcanize.

Are you using any other processing/minification tools except vulcanize in your chain? Please try to provide an isolated example.

**Comment by platosha** [comment] 2017-05-26 10:11
Closing because can’t reproduce. Feel free to reopen if still relevant.

**Closed by platosha** 2017-05-26 10:11 UTC
