### ISSUE TITLE
Setting initial custom value for vaadin-combo-box-light doesn't work

### ISSUE THREAD

**Issue by panuhorsmalahti** [vaadin/vaadin-combo-box#325] opened 2016-10-14 10:52 UTC
When I'm initializing the vaadin-combo-box-light with a value found from the dropdown items everything works fine. If I initialize it with a value not found from the dropdown items the underlying element's `value` is set to `""` instead of the custom value. I'm using `allow-custom-value`.

My template is as follows:

```
      <vaadin-combo-box-light
        items="[[ autocompleteItems ]]"
        allow-custom-value="true"
        attr-for-value="value"
        selected-item="{{ selectedItem }}"
        value="[[ value ]]")>
        <paper-input no-label-float="true" >
          <paper-icon-button(suffix icon="vaadin-combo-box:arrow-drop-down" noink>
```

If I use the debugger I can see that the vaadin-combo-box-light `.value` is e.g. "foo", but paper-input `.value` is `""`, e.g. no value is displayed.

Once I select something from either the dropdown list or by just typing the paper-input's value and vaadin-combo-box-light's value are synced (and work correctly).

My (very ugly) workaround currently is to set it manually:

```
        attached() {
            setTimeout(() => {
                if (this.$$("#vaadincombo")) {
                   window.wrap(this.$$("#vaadincombo"))._inputElementValue = this.value;
                }
            });
        },
```

**Comment by samiheikki** [comment] 2016-10-25 09:36
I can confirm that this is a bug. Fixing it will be non-trivial as the problem is with `set _inputElementValue` and `vaadin-combo-box-light`'s `attached` lifecycle's order.

**Comment by samiheikki** [comment] 2019-06-24 05:12
This has been fixed in an earlier commit.

My test code: 
```
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />
  <title>vaadin-combo-box Examples</title>
  <script src="../../webcomponentsjs/webcomponents-lite.js"></script>

  <link rel="import" href="../../polymer/polymer.html">
  <link rel="import" href="../../polymer/lib/elements/dom-bind.html">
  <script src="../../vaadin-demo-helpers/vaadin-demo-ready-event-emitter.js"></script>

  <script src="combo-box-demo.js"></script>

  <link rel="import" href="../vaadin-combo-box-light.html">
  <link rel="import" href="../../iron-input/iron-input.html">

  <style>
    vaadin-combo-box-light {
      margin-top: 25px;
      display: block;
    }

    iron-input, input {
      width: 100%;
    }
  </style>
</head>

<body>
  <dom-bind>
    <template is="dom-bind">
      <vaadin-combo-box-light attr-for-value="bind-value" allow-custom-value value="[[initialValue]]" items="[[items]]">
        <iron-input>
          <input>
        </iron-input>
      </vaadin-combo-box-light>
    </template>
  </dom-bind>

  <script>
    customElements.whenDefined('vaadin-combo-box-light').then(function() {
      var autobind = document.querySelector('dom-bind');
      autobind.items = elements;
      autobind.initialValue = "Hello";
    });
  </script>
</body>
</html>




```
Outputs this:
<img width="850" alt="Screenshot 2019-06-24 at 8 10 30" src="https://user-images.githubusercontent.com/8615573/59993091-92c1b400-9657-11e9-8d75-44e85941e71a.png">

Closing the issue.

**Closed by samiheikki** 2019-06-24 05:12 UTC
Labels: bug
