### ISSUE TITLE
Page scrollbar disappears and content shifts to the right after clicking inside combo box

### ISSUE THREAD

**Issue by ivan** [vaadin/vaadin-combo-box#101] opened 2016-01-05 05:33 UTC
With Chrome 47 on Ubuntu, clicking inside the input field of the combo box on https://cdn.vaadin.com/vaadin-elements/master/vaadin-combo-box/demo/ causes the page scrollbar to disappear and shifts the page content to the right.  I'm guessing this also happens on Windows but not on OS X where the scrollbar is hidden?

**Comment by Saulis** [comment] 2016-01-05 08:12
Yeah, this is caused by `<iron-dropdown>` preventing scrolling when open. I'm closing this ticket as a duplicate for #78. Would you be kind enough to add a +1 there as a comment to indicate that you've also encountered the issue? Thanks!

**Closed by Saulis** 2016-01-05 08:12 UTC
