### ISSUE TITLE
Dropdown shown below the error message

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-combo-box#969] opened 2020-11-11 14:55 UTC
### Description
The dropdown is shown below the error message, creating an unexpected space between the Combo and the Dropdown, which looks funny.

![Screenshot from 2020-11-11 16-54-36](https://user-images.githubusercontent.com/254091/98826633-9e756c80-243e-11eb-8e74-f361544099a5.png)

### Expected outcome
The dropdown should show right below the combobox.

### Actual outcome
dropdown is shown below the error message

### Steps to reproduce
```java
@Route("")
@PWA(name = "Project Base for Vaadin", shortName = "Project Base", enableInstallPrompt = false)
public class MainView extends VerticalLayout {

    public MainView() {
        final ComboBox<String> combo = new ComboBox<>();
        combo.setItems("aaa", "bbb", "ccc");
        combo.setErrorMessage("Hello");
        combo.setInvalid(true);
        add(combo);
    }
}
```

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by DiegoCardoso** [comment] 2020-11-11 15:49
Thanks for the issue. There's already another one, which cover this.

Closing as duplicate of #549

**Closed by DiegoCardoso** 2020-11-11 15:49 UTC
