### ISSUE TITLE
Combo box failing on setItems() after upgrade to Vaadin 12

### ISSUE THREAD

**Issue by brunojcm** [vaadin/vaadin-combo-box#755] opened 2018-12-13 15:51 UTC
### Description
I have two combos here, one updating the list of the other one:

```kotlin
                val purchaseOrders = comboBox<PurchaseOrder>("Purchase Order") {
                    width = "18em"
                    itemLabelGenerator = ItemLabelGenerator { it.codeWithAlias }
                    isReadOnly = true
                }
                costCenters.addValueChangeListener {
                    if (it.value != null) {
                        val project = it.value as Project
                        val poList = purchaseOrderService.availablePurchaseOrders(project.client, project)

                        purchaseOrders.setItems(poList)
                        purchaseOrders.isReadOnly = poList.isEmpty()
                        return@addValueChangeListener
                    }
                    purchaseOrders.setItems(listOf())
                    purchaseOrders.isReadOnly = true
                }
```

### Expected outcome
On Vaadin 11.0.2, everything works fine and after a change the first combo, the second one is updated with the proper records.

### Actual outcome
After upgrading to Vaadin 12.0.0 (combo-box 4.2.0), the following errors show on the client side only, and no elements in the combo drop-down:

(TypeError) : Cannot read property 'confirm' of undefined
(TypeError) : Cannot read property 'reset' of undefined
(TypeError) : Cannot read property 'set' of undefined
(TypeError) : Cannot read property 'updateSize' of undefined

### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by voodoohoo** [comment] 2018-12-20 13:05
Hi brunojcm,

we mentioned the very same problem after upgrading to v12.0.3 with vaadin-combo-box-flow
Could you please try to call setItems outside the ValueChangeListener with an empty list?

We did so and the setItem call within the ValueChangeListener filled the combobox correctly again

Regards

**Comment by web-padawan** [comment] 2018-12-20 14:02
Thanks for the issue. Closing as a duplicate of vaadin/vaadin-combo-box-flow#169

**Closed by web-padawan** 2018-12-20 14:02 UTC

**Comment by brunojcm** [comment] 2018-12-26 23:03
> Could you please try to call setItems outside the ValueChangeListener with an empty list?

That worked, thanks!
