### ISSUE TITLE
Setting value to empty string does no clears the combobox.

### ISSUE THREAD

**Issue by sz332** [vaadin/vaadin-combo-box#372] opened 2017-01-15 07:48 UTC
### Description

element.value does not deselect previous entry from combobox. Also when checking for value change,
the previous value is sent again.

### Expected outcome

When setting element.value to "" then combobox should be deselected, and when setting new value, the previously selected value shall be not selected.

### Actual outcome

As in description.

### Live Demo

https://jsfiddle.net/0qv884zs/

### Steps to reproduce

Create a new vaadin-combo-box.
Set default entries. 
Create a function listening to value change.
In this function set value to empty string.

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [?] Safari
- [?] Edge
- [?] IE 11
- [?] iOS Safari
- [?] Android Chrome

**Comment by Saulis** [comment] 2017-01-16 08:02
The problem in your example app is that you're trying to set `value` while inside a `value-changed` listener which can create a loop. 

What is the use case you're after?

Normally, a user-triggered value clearing works just fine: https://jsfiddle.net/Saulis/Ld26L0cs/

**Comment by sz332** [comment] 2017-01-16 08:04
Hello,

my goal was to create a tag component, where the user can choose a value from a combobox, and if it is choosen, the new entry is added to the list of selected tags, and the combobox is cleared, so he can choose another tag.

**Comment by Saulis** [comment] 2017-01-23 09:12
As discussed in Gitter, I think #88 is the solution for your use-case.

**Comment by tomivirkki** [comment] 2018-05-16 11:30
The issue is still there (not able to clear the value in a value-changed listener). Closing as a duplicate of https://github.com/vaadin/vaadin-combo-box/issues/651

**Closed by tomivirkki** 2018-05-16 11:30 UTC
