### ISSUE TITLE
Empty combobox feels broken

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-combo-box#660] opened 2018-05-23 11:05 UTC
### Description
If you for whatever reason create an empty combo box: `<vaadin-combo-box>` but think you have added items to it, it's hard to realize that it's not broken but just has no items:
1. Nothing seemingly happens when you open the popup

UPD: already fixed
~2. The state changes between "hidden opening closing" and "hidden opening closing opened"
3. Each time you open/close the combo box, a `<!--vaadin-overlay-placeholder-->` comment is added to the body~

### Expected outcome
It is visually clear that the combo box contains no items

### Actual outcome
There is no indication that anything happens when clicking the dropdown button

### Steps to reproduce
Tested using https://vaadin.com/components/vaadin-combo-box/html-examples/combo-box-basic-demos by setting `items = [];`

### Browsers Affected

Only tested in Chrome
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by web-padawan** [comment] 2019-01-29 07:31
Appears to be fixed on master, especially versions 4.1.0 and after work normally
However, seems to be still valid for V10 and so needs to be fixed for 4.0.x

**Comment by web-padawan** [comment] 2019-01-29 07:35
Most likely fixed by #684, need to confirm and if that helps, cherry pick to `vaadin10` branch

**Comment by web-padawan** [comment] 2019-01-29 13:40
Note: the PR targeting this issue is only fixing the 2. and 3.
Regarding the visual indication, that's a separate thing which should be also handled somehow.

Would it make any sense to add `console.warn` in case of the following:
- `items` array is empty
- `dataProvider` returned 0 items
- `allowCustomValue` is set to false?

**Comment by web-padawan** [comment] 2019-01-30 07:01
Just realised that now (after 2. and 3. are fixed) the remaining part is duplicate of #162 
There is a pending PR for it at #550 so let's keep that in mind. Closing this as fixed.

**Closed by web-padawan** 2019-01-30 07:01 UTC
Labels: good first issue, in review
