### ISSUE TITLE
Custom Styled ComboBox is arranged Vertical

### ISSUE THREAD

**Issue by jogibear9988** [vaadin/vaadin-combo-box#624] opened 2018-03-06 10:43 UTC
I've copied the code from your example: "Replacing the Input with a <paper-input>"

If I do so, I got the following Layout:

![aa](https://user-images.githubusercontent.com/364896/37028048-7568c460-2133-11e8-9c5f-d56a5403ac52.png)

Version: 3.0.3

**Comment by jogibear9988** [comment] 2018-03-06 10:43
And the buttons also have no effect...

**Comment by web-padawan** [comment] 2020-02-18 14:26
Sorry for not answering earlier. We no longer have this example in our demos.
But actually nothing has changed in `vaadin-combo-box-light` since then.

I was unable to reproduce this in glitch: buttons work, appearance seems to be correct.
See demo: https://glitch.com/edit/#!/combo-box-light-paper-input?path=index.html:11:0

Closing because this issue is outdated and lacks a proper reproduction.

**Closed by web-padawan** 2020-02-18 14:26 UTC
