### ISSUE TITLE
Popup sometimes closed for click event with stopPropagation

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-combo-box#766] opened 2019-02-06 09:56 UTC
If you add a button inside the combo box popup, and call `event.stopPropagation()` for the click listener, it would be expected that the popup stays open when the button is clicked.

See example case in [vaadin/vaadin-overlay#144](https://github.com/vaadin/vaadin-overlay/issues/144)

When opening the test page and the popup is open, clicking on the 'edit' button opens a dialog and the combobox popup stays open.

If you instead open the test page, click on the background, open the combo box again and then click 'edit', the combo box overlay is closed when the dialog is shown.

### Browsers Affected
- [X] Chrome, only browser tested

**Comment by tomivirkki** [comment] 2019-05-09 12:39
Is this still an issue?

**Comment by web-padawan** [comment] 2019-06-04 08:58
The reason is that combo-box closes on `focusout`, which is expected behavior. When opening dialog, focus moves there - naturally, combo-box is then lurred and closed.

That doesn't happen when clicking button on the pre-opened combo-box in the example case linked from the original issue, because it doesn't contain focus (so no `focusout` event happens).

Attempting to workaround this does not seem right too me. We don't know where the focus will move at the time of `focusout`, and prevented click event seems quite an edge case.

**Comment by web-padawan** [comment] 2019-06-11 10:37
If you need to force this behavior, consider trying to call `e.preventDefault()` on the item `mousedown` event. That also prevents native `focusout` event, so the combo-box should stay open.

Closing, let's reopen if we get more feedback on the actual use cases.

**Closed by web-padawan** 2019-06-11 10:37 UTC
