### ISSUE TITLE
vaadin-combo-box when placed inside paper-dialog is closing the dialog in some cases. 

### ISSUE THREAD

**Issue by GoceRibeski** [vaadin/vaadin-combo-box#405] opened 2017-02-21 12:58 UTC
### Description
When `vaadin-combo-box` element  is placed inside paper-dialog, if user opens the box for selection(but does not select, just  leaves it opened ) then click anywhere in the dialog closes the dialog.

### Expected outcome
Click anywhere in the dialog( pr. top left corner) should close the box, but leave the dialog opened.

### Actual outcome
Click anywhere in the dialog closes the whole dialog.

### Live Demo
https://jsfiddle.net/ribe/02tntfn3/2/

### Steps to reproduce

1. Open the dialog, 
2. open the box, and do not select - leave it opened,
3.Click on the top left corner of the dialog.

**Comment by web-padawan** [comment] 2017-02-21 13:07
There is a kind of bug with events propagation. E. g. closing `vaadin-combo-box` by pressing Esc also closes dialog. In such cases I usually use something like `on-keydown="_stopPropagation"` and then just add handler like this:
```
_stopPropafation: function (e) {
  e.stopPropagation()
}
```
There's also a `stopKeyboardEventPropagation` property supplied by [IronA11yKeysBehavior ](https://elements.polymer-project.org/elements/iron-a11y-keys?active=Polymer.IronA11yKeysBehavior), but that behavior is not  implemented by `vaadin-combo-box` and that property seems not to work for some other elements, looks like it handles events too late.

**Comment by GoceRibeski** [comment] 2017-02-21 18:12
I can't find where to place the event that will call `stopPropagation` in given Fiddle. Any idea?

**Comment by Saulis** [comment] 2017-03-01 06:59
Hi there!

The challenge here is that the overlay of `<vaadin-combo-box>` is placed under `<body>`, which is outside of the `<paper-dialog>` so it considers any clicks on the combo-box's overlay as "outside clicks", which by default close the dialog.

As a workaround, you can disable the outside clicks when the combo-box is open:

```html
...
<vaadin-combo-box id="third" label="Focus Third" tabindex="3" on-focus="_focusInput" items="[[items]]" on-blur="_onBlur" on-opened-changed="_onComboBoxOpened">
        </vaadin-combo-box>

<script>
...
_onComboBoxOpened: function(e) {
  if (e.detail.value) {
    this.$.add_row_details_dialog.noCancelOnOutsideClick = true;
  } else {
    this.async(function() {
      this.$.add_row_details_dialog.noCancelOnOutsideClick = false;
    }, 10);
  }
}
...
</script>
```

**Comment by kito99** [comment] 2017-03-02 15:21
@Saulis, your approach didn't work for me, unfortunately. However, I just set the noCancelOnOutsideClick property to true on the paper-dialog, and that fixes the problem (there was no requirement to close the dialog when you click outside of it, in this case).

**Comment by kito99** [comment] 2017-03-02 15:25
FYI, this also happens if you just select an item in the combo box using your mouse...

**Comment by artem-vladimirov** [comment] 2017-03-17 17:53
Apply  'no-cancel-on-outside-click' to paper-dialog element that will prevent closing the dialog when you selected element in the vaadin-combo-box by mouseclick or from keyboard.

`<paper-dialog no-cancel-on-outside-click>
        <vaadin-combo-box class="elements-box" items="[[arrayOfValues]]"></vaadin-combo-box>
    </paper-dialog>`

**Comment by panuhorsmalahti** [comment] 2017-04-03 07:58
@kito99 / @artem-vladimirov 's workaround with no-cancel-on-outside-click is not suitable in general or for me, since I want the user to be able to close the dialog with an outside click.

I can confirm @kito99's observation that just selecting an item closes the dialog, and so does canceling the selection by clicking on the paper-dialog.

**Comment by timoteoponce** [comment] 2017-05-10 14:22
Is there something to do here besides to wait a new version? official vaadin workaround?

**Comment by jouni** [comment] 2017-05-10 18:54
Not sure why I’ve completely missed this issue for so long. This is a really fundamental usability problem and should be fixed asap. I’ll see if I can inspire @Saulis or someone else from the dev team to take a look this or next week.

**Comment by Saulis** [comment] 2017-05-10 20:25
Hey guys, please try out the branch `iron-overlay-cancel` (unfortunately that's built on top of current master so there might be some dependency conflicts with it being hybrid)

I also cherry-picked the change on top of the `1.x` branch (`iron-overlay-cancel-v1`) but can't currently verify it working myself as I don't want to mess up my Polymer 2 bower setup :-)

**Comment by Saulis** [comment] 2017-06-12 05:52
@GoceRibeski @web-padawan @kito99 @artem-vladimirov @panuhorsmalahti @timoteoponce anybody have a chance to try the fix out? Thanks!

**Comment by web-padawan** [comment] 2017-06-12 06:23
@Saulis Thanks for reminding. I just grabbed the `iron-overlay-cancel-v1` branch and I see the warning:
```
[vaadin-combo-box::_createEventHandler]: listener method `_onBlur` not defined
```
So, after having both `paper-dialog` and inner `vaadin-combo-box` opened, I tried two things:

1. When pressing Esc key, dialog gets closed while combo-box overlay stays opened,
2. When selecting item, both dialog and combo box get closed. 

I have not much time to investigate right now, but guess that missing listener might be the reason.

**Comment by Saulis** [comment] 2017-06-12 06:33
@web-padawan thanks! no need to worry about the missing `_onBlur`, its a listener that is intentionally removed, but the accidentally left the listener binding in place. I need to re-test those issues you reported, I haven't tested the v1 branch myself.

**Comment by Saulis** [comment] 2017-06-12 07:06
@web-padawan I can confirm that the fix does work for me both on `iron-overlay-cancel` with Polymer 2.x and `iron-overlay-cancel-v1` Polymer `1.9.1` – please double-check that you have `iron-overlay-behavior` `v1.10.3` or later installed (I'm running `2.0.0`)

**Comment by arkihillel** [comment] 2017-06-12 09:29
@Saulis It doesn't work for me. In fact I even have a weird bug that is not present on 2.0a4. All the text from my template disappears

I'm running Polymer 2 with `iron-overlay-behavior#2.0.0` 

Here is `2.0.0-alpha4`: http://www.giphy.com/gifs/3ohzdQKeVtoswDSpfW
Here is the `iron-overlay-cancel` branch: http://www.giphy.com/gifs/3o7btZ3T0yMwKkG6fm

**Comment by Saulis** [comment] 2017-06-12 12:37
@arkihillel I've rebased `iron-overlay-cancel` on top of `master`, can you try again? And make sure you reinstall all bower deps.

**Comment by jonagh** [comment] 2017-06-12 21:20
Seems to work for me.
Using: vaadin-combo-box#iron-overlay-cancel, polymer#2.0.1, iron-overlay-behavior#2.0.0

Btw, not a big deal, but you may have made a typo with `_removeOutsideTabListener`, ie Tab vs Tap ;)

**Comment by arkihillel** [comment] 2017-06-12 22:27
@Saulis Reinstalling the dependencies didn't work for me but I found the issue
The thing is that I have a `close()` function attached to a closing icon to close my dialog

For some reason, whenever I click on an item the function is called and subsequently closes the dialog. 

Thanks you very much for the fix. I'm happy to finally have something working but I'm pretty sure this is not supposed to happen. Sounds like it violates the Shadow DOM component encapsulation principle but I might be wrong.

Here is the content of the event, not sure why it's caught by my `close` function:
![image](https://user-images.githubusercontent.com/3636434/27057215-751774fa-4fcb-11e7-9a98-b64d7c24c39f.png)

**Comment by JuanCalderon** [comment] 2017-08-04 18:49
Is there already a stable solution ?
When an Item is selected using the mouse, the event (selectedItemChange) is triggered two times; the first with the new selected Item and the second with the previous (impossible change the selection).
Thanks.

**Closed** 2017-08-17 11:57 UTC
