### ISSUE TITLE
Cannot read property 'overlay' of undefined

### ISSUE THREAD

**Issue by pedronim** [vaadin/vaadin-combo-box#983] opened 2020-12-17 11:20 UTC
I'm not sure if I'm actually posting this to the right place & hope it finds its way there magically... 😉 

### Description
Grid with ComboBox component column produces error in the browser Console ("Cannot read property 'overlay' of undefined"), if there are a large number of rows in the grid.

### Vaadin flow Java code example
```public class MainView extends VerticalLayout {

    public MainView() {
        Grid<Person> internalGrid = new Grid<>();
        List<Country> countries = Arrays.asList(new Country("Country A"), new Country("Country B"), new Country("Country C"));
        List<Person> persons = new ArrayList<>();
        for (int i = 0; i < 100; i++) {
            persons.add(new Person("Person " + i, countries.get(i % 3)));
        }

        internalGrid.addColumn(Person::getLastName);
        internalGrid.addComponentColumn( item -> {
            ComboBox<Country> comboBox = new ComboBox<> ();
            comboBox.setDataProvider(new ListDataProvider<>(countries));
            comboBox.setItemLabelGenerator(Country::getName);
            comboBox.setValue(item.getNationality());
            comboBox.addValueChangeListener(event -> item.setNationality(event.getValue()));
            comboBox.setWidthFull();
            return comboBox;
        });
        add(internalGrid);
        internalGrid.setDataProvider(DataProvider.fromCallbacks(
            query -> persons.subList(query.getOffset(), query.getOffset() + query.getLimit()).stream(),
            query -> persons.size()
        ));
    }
}
```

### Steps to reproduce
1. Create a grid with a ComboBox as a component column and a callback data provider.
2. Add lots of elements (I got the error with 100 elements, only adding 3 elements did not produce any error)
3. Open the page in a web browser.
4. Check the browser's Console.

### Expected Results
No errors in console. 

### Actual Results
Everything works fine, but there is an error in the Console that should be submitted:
```
Cannot read property 'overlay' of undefined
Please submit an issue to https://github.com/vaadin/vaadin-combo-box-flow/issues/new!
```

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Safari
- [?] iOS Safari
- [?] Android Chrome

### Version
Multiple versions (I think), e.g. "@vaadin/vaadin-combo-box": "5.4.6",

**Comment by yuriy-fix** [comment] 2020-12-22 11:46
Seems to be related https://github.com/vaadin/vaadin-combo-box/issues/959

**Comment by DiegoCardoso** [comment] 2020-12-23 09:28
Confirmed the issue and that it's related to #959.

I added some details there (https://github.com/vaadin/vaadin-combo-box/issues/959#issuecomment-750035059)

Closing as duplicate. 

Thanks for the report.

**Closed by DiegoCardoso** 2020-12-23 09:28 UTC
Labels: Impact: Low, Severity: Major
