### ISSUE TITLE
Neither 'selected-item-changed' nor 'value-changed' events bubble

### ISSUE THREAD

**Issue by secondfry** [vaadin/vaadin-combo-box#220] opened 2016-04-14 15:14 UTC
Hello. subj.
This prevents you from dynamically listening on higher node which is sad.

Also when you do create nodes from backend HTML chunks, you can't create local event listeners on child nodes without iterating them. Kinda dirty way of creating nodes but it's common.

So is it intended behavior that won't change or bug which gonna be fixed?

**Comment by Saulis** [comment] 2016-04-15 05:56
Hi!

The [property change events](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#change-notification-protocol) where using are *non-*bubbling by default in Polymer.

I tried to look for information on this (why it is non-bubbling, can it be set to bubbling) but couldn't find much anything. 

So yes, it is intended behaviour by Polymer and at this point I can't unfortunately promise that there would be something we could do about it.

As a workaround I would suggest that you wrap the `vaadin-combo-box` inside a custom element that listens to `value-changed` and `selected-item-changed` events and fires custom events that do bubble.

**Comment by Saulis** [comment] 2016-04-25 06:25
I'm going to close this issue for now, since the current behaviour is the de-facto Polymer behaviour. 

Feel free to reopen if you think I've missed something.

**Closed by Saulis** 2016-04-25 06:25 UTC
