### ISSUE TITLE
Combobox display flickering when changing cycling through items with the arrow keys

### ISSUE THREAD

**Issue by andreasbean** [vaadin/vaadin-combo-box#790] opened 2019-03-15 16:33 UTC
Steps to reproduce

1) create a ComboBox and set a placeholder text
2) set items
3) when the drop down is open and the items are cycles through with the up/down keys then the placeholder text appears for a short time before the next item is shown in the text field.

**Comment by Haprog** [comment] 2019-03-19 11:31
Closing as a duplicate of #662.

**Closed by Haprog** 2019-03-19 11:31 UTC
