### ISSUE TITLE
Deleting characters do not always return cursor to correct position on iOS

### ISSUE THREAD

**Issue by tehapo** [vaadin/vaadin-combo-box#116] opened 2016-01-26 08:18 UTC
Typing and deleting a character does not always return the cursor to correct position on iOS. Visually it looks like there is an extra space in the beginning. Pressing backspace again will delete it and return cursor to the beginning of the field. See attached Gif for demo of the situation.

Notice that the extra space also automatically disappears if one starts typing again while the space is visible (i.e. resulting typed text without any space in the beginning).

![delete-cursor-position](https://cloud.githubusercontent.com/assets/368220/12575547/f1685260-c415-11e5-9fc1-12e1b093d13c.gif)

**Comment by samiheikki** [comment] 2016-10-27 12:40
Can't reproduce on iOS (10) Safari/Chrome/FF. Closing this issue now. Probably been fixed in some paper-input update.

**Closed by samiheikki** 2016-10-27 12:40 UTC
