### ISSUE TITLE
Combobox with lazy loading and autoOpenDisabled fails

### ISSUE THREAD

**Issue by Manfred-on-github** [vaadin/vaadin-combo-box#992] opened 2021-01-25 14:16 UTC
### Description
combobox via FLOW from java, items are provided via FetchCallback, we have setAutoOpen(false).

When clicking open the combobox with empty text field, it works correctly.

However when you first enter some character (as initial filter), then click open, you only see the "loading" indicator, no items are displayed.

### Sample code
`@Route(value = "combobox")
public class ComboboxLoadingBug extends VerticalLayout {
	
	List<Item> allItems;
	
	public ComboboxLoadingBug() {
		add(getCombobox());
		add(new TextField("Hello"));//to see 'TAB' working 
		allItems = IntStream.range(1, 100).mapToObj(i -> new Item(i)).collect(toList());
	}

	private Component getCombobox() {
		ComboBox<Item> cb = new ComboBox<>();
		cb.setItems(qu -> getItems(qu));
		cb.setAllowCustomValue(true);
		cb.setAutoOpen(false);
		cb.addValueChangeListener(e -> valueChanged(e));
		cb.addCustomValueSetListener(e -> customValue(e));
		cb.getElement().addPropertyChangeListener("filter", e -> filterPropChanged(e));
		return cb;
	}

	private void filterPropChanged(PropertyChangeEvent e) {
		System.out.println("filter prop changed: " + e.getValue());
	}

	private void customValue(CustomValueSetEvent<ComboBox<Item>> e) {
		System.out.println("custom value " + e.getDetail());
	}

	private void valueChanged(ComponentValueChangeEvent<ComboBox<Item>, Item> e) {
		System.out.println("Value changed: " +e.getValue());
	}

	private Stream<Item> getItems(Query<Item, String> qu) {
		System.out.println("Query: |" + qu.getFilter().orElse("<undefined>") + "|");
		return allItems.stream()
					.filter(i -> filter(i, qu.getFilter()))
					.skip(qu.getOffset()).limit(qu.getLimit());
	}

	private boolean filter(Item i, Optional<String> filter) {
		return filter.map(f -> i.toString().startsWith(f)).orElse(true);
	}

	private static class Item {
		int i;
		Item(int i) {this.i = i;}
		
		@Override
		public String toString() {
			return  String.format("%02d", i);
		}		
	}`

### Steps to reproduce
using the sample code above
1. put focus to combobox, type some character (e.g. '4')
2. click the 'open' button

### Expected Results
The list should appear, properly filtered

### Actual Results
the overlay with list appears, but only shows the 'loading' icon

### Browsers Affected
probably all, but checked with
- [x ] Chrome

### Version
- vaadin-combo-box: v5.4.6
- vaadin-combobox-flow-18.0.1.jar

### additional information
this is probably related to #963, it had worked in some previous release (cannot specify exactly at the moment).

looking deeper into what happens I found the following:
typing '4' causes 'filter' property to change, which causes #loadPage() to get invoked, setting attribute 'loading'.
On the java side, the lazy data provider has caused the flag DataCommunicator.fetchEnabled to be false, so the above request never returns any result, therefore the 'loading' never gets cleared on the client.

### desired functionality (request for enhancement)
When you correct this, the behavior of the combobox together with lazy loading is still not exactly as desired for our application.
So it would be very helpful if the following could be possible:
- we typically have many comboboxes in a screen, it is a complex task to retrieve from backend all items for all comboboxes when the screen opens, especially since the user might never open any of them. Therefore we rely on the lazy-loading feature.
- some experienced users know the id's of the items, so they are quickest in just typing the id (e.g. '42' in the sample code) then tab out to next field. We can handle this smoothly when we are informed about this input. Vaadin-Combobox has available the event 'custom-value-set' for this. This event should however only be sent when the user actually terminates input by tabbing out, not when typing something and then clicking 'open'. At least we should be able to differentiate between the two situations when this event comes in.
- While the user is typing some characters to filter values, the query to fill the data provider should only come when user actually wants to see the values (i.e. opens the list). Otherwise we would be retrieving lots of data from backend which the user might never see (especially in the case above, user types and then tabs out).
- it should be possible to fill the text control with some "current value", while leaving the items empty, the (lazy) data provider should not be invoked in this case, but only when user opens the combobox.

**Comment by yuriy-fix** [comment] 2021-01-27 09:47
Dear @Manfred-on-github, 
Can I ask you to create a separate issue for the enhancements mentioned in this ticket, so that one can be marked properly?

**Comment by Manfred-on-github** [comment] 2021-01-27 10:18
as per your request have created #993 for the wishes about event handling when user types while combobox is closed. 

When examining this bug here, please keep in mind the considerations mentioned there, since this may direct you to some simple solution (e.g. never do any filter, query items from backend, while combobox is closed - at least when combobox is in such lazy mode - is this 'autoOpenDisabled==true', or a new flag?).

**Comment by sosa-vaadin** [comment] 2021-02-21 15:02
I was unable to reproduce the issue described in this ticket. However, I found another problem. When the combo-box is closed and anything is written in the combo-box and then the `open` button is clicked, the list is loaded in full, as if the user did not write anything in the filter. While the combo-box is open, if the user changes the value of the filter, the combo-box then filters correctly.

https://user-images.githubusercontent.com/76832183/108628953-5830a000-7466-11eb-9f30-e6803824b213.mov

The user expects the list to only contain filtered values when opening the combo-box. Yet, the component loads the list with an "empty" filter when opening the list.

**Comment by sosa-vaadin** [comment] 2021-02-23 14:17
Since I'm unable to reproduce the original bug, I'm closing this and opening #1000 to describe the new problem found.

**Comment by Manfred-on-github** [comment] 2021-02-23 15:04
Just to be sure to get rid of any influences from our application, have now created a spring-boot project from one of vaadin starter applications (now using vaadin 18.0.6), inserted my testcode (from above) and I can still reproduce the problem.

regarding to your video: you are not supposed to open the combobox (and thus load the list) in the beginning.
My scenario is as follows: open the screen, the list of combobox must not be loaded ("lazy loading"). Then type '4', and immediately click to open the combobox.

**Comment by sosa-vaadin** [comment] 2021-02-24 09:26
Cannot reproduce in LTS version (Vaadin 14).
Can reproduce in v18.0.6

**Closed** 2021-04-20 14:47 UTC
Labels: Impact: High, Severity: Major
