### ISSUE TITLE
Selecting object value returns string "[object Object]"

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/vaadin-combo-box#639] opened 2018-04-10 04:58 UTC
Using 4.0.0-beta4

```
<vaadin-combo-box id="select" item-label-path="foo" items="[[items]]"
      value="{{selected}}"></vaadin-combo-box>

------------

          items: {
            type: Array,
            value: () => [{
              foo: 'foo',
              bar: 'bar'
            },
            {
              foo: 'foo2',
              bar: 'bar2'
            }]
          }

```

GIven the example above, I would expect that the `selected` property would contain the selected object, but instead it contains the string value "[object Object]"

**Comment by jouni** [comment] 2018-04-10 05:40
This is expected behavior. The `value` property is always a `String`, for form submission.

Use the `selectedItem` property instead, or the `itemValuePath` property to map to a sub-property in the item which should be used as the value.

**Comment by web-padawan** [comment] 2020-02-18 14:50
Closing as won't fix (working as intended) per above comment.

**Closed by web-padawan** 2020-02-18 14:50 UTC
Labels: wontfix
