### ISSUE TITLE
selected-item-changed called multiple times

### ISSUE THREAD

**Issue by Bretto** [vaadin/vaadin-combo-box#295] opened 2016-08-23 05:52 UTC
I am using it with Ng2 and my methode: 

```
<vaadin-combo-box
        label="Tags"
        item-label-path="name"
        [items]="tags"
        (selected-item-changed)="onSelect($event.detail.value)"></vaadin-combo-box>
```

**onSelect** is called 3 times per selection

**Comment by Saulis** [comment] 2016-10-03 07:31
Hi!

Is the `$event.detail.value` value different on each call?

**Comment by asaph26** [comment] 2016-10-17 19:17
@Saulis In my case, it was different for the 2 calls. The first call always contains the first element and the second call contains the actual selected item.

I had to rely on using the selectedItem while listening to the value-changed event

**Comment by jouni** [comment] 2016-11-07 20:10
Is #330 caused by the same issue as this?

**Comment by asaph26** [comment] 2016-11-08 20:42
@jouni In my case, the value-changed event was fired only once. So I am not sure what causes it. I remembered reading somewhere that the double event was likely caused because of the event being triggered by both the vaadin-combo-box and the Iron Form Element Behaviour

**Comment by Saulis** [comment] 2016-12-19 15:57
Probably related with #359 (not using `item-value-path`)

**Comment by platosha** [comment] 2017-05-26 12:32
Closing for now. Seems this was caused by the same as #359, which was fixed a while ago.

Feel free to respond if this is still occur.

Note that there is a workaround possible using the `change` event, which is dispatched only after user changes.

**Closed by platosha** 2017-05-26 12:32 UTC
