### ISSUE TITLE
Custom value focus issue

### ISSUE THREAD

**Issue by avix89** [vaadin/vaadin-combo-box#719] opened 2018-09-18 06:22 UTC
### Description
I have a form which contains some vaadin-combo-boxes (with custom value feature so that a user can give custom value apart from the already existing options.) and a search button .

### Expected outcome
Now whenever a user type something in that combobox which is not part of already defined options and after typing user moves mouse over that search button it shhould get focus and should trigger search button on first click.

### Actual outcome
But outcome is different as user has to click two times on that search button to trigger the search event.

### Steps to reproduce
1. Put a `vaadin-combo-box` element in the page like this `<vaadin-combo-box id="testcombo" items="{{someList}}"  allow-custom-value></vaadin-combo-box >` and a  vaadin button like this  `<vaadin-button aria-label="Search"  on-click="searchPerformed"> Search  </vaadin-button>`

2. Open the page in a Chrom web browser.
3. Type something random in that combo box .
4. After typing directly click on that search button.

### Browsers Affected

- [ check] Chrome

**Comment by web-padawan** [comment] 2018-09-18 06:34
Thanks for the issue, could you create a live demo using this glitch in the issue template?
https://glitch.com/edit/#!/capricious-bug

**Comment by jouni** [comment] 2018-09-18 08:44
The issue is in the modal overlay/dropdown, which is still technically open even though it’s not showing any items or even visible on the screen. The overlay has an invisible modality curtain which blocks clicks/taps on the page when the overlay is open.

The first click outside the combo-box closes the overlay (and moves the focus the input field) and then the second click can click the search button.

Should be fixed by actually closing the overlay/dropdown when there are no matching items to show in it.

**Comment by avix89** [comment] 2018-09-19 04:00
> The issue is in the modal overlay/dropdown, which is still technically open even though it’s not showing any items or even visible on the screen. The overlay has an invisible modality curtain which blocks clicks/taps on the page when the overlay is open.
> 
> The first click outside the combo-box closes the overlay (and moves the focus the input field) and then the second click can click the search button.
> 
> Should be fixed by actually closing the overlay/dropdown when there are no matching items to show in it.

Can You provide any temporary solution for that?

**Comment by jouni** [comment] 2018-09-19 05:53
> Can You provide any temporary solution for that?

I suppose you could disable the dropdown modality completely by setting `body { pointer-events: auto !important; }` in your global stylesheet. That might have some other unseen side-effects (if some other component relies on the `pointer-events` value, so you need to take that into consideration.

**Comment by Canuckaholic** [comment] 2020-08-27 20:21
We're experiencing this issue on a current project. Was a fix ever implemented by any chance?

**Comment by rolfsmeds** [comment] 2020-10-22 13:02
@Canuckaholic and @avix89, would you consider the solution in this ticket to also solve your problem? https://github.com/vaadin/vaadin-overlay/issues/185
(essentially allowing you to disabled the modality of overlays entirely, regardless of whether those overlays are visible or not)

**Closed** 2020-11-02 10:37 UTC
Labels: BFP, bug
