### ISSUE TITLE
Styling combo box items

### ISSUE THREAD

**Issue by steffen-harbich-itc** [vaadin/vaadin-combo-box#820] opened 2019-03-28 10:11 UTC
I would like to use external styles in combo box items but this doesn't work since the items are within the shadow dom. 

The concrete scenario is to show flag icons in a language selection combo box using [flag-icon-css](https://github.com/lipis/flag-icon-css). For the flags to be shown, a span tag with some CSS classes from the flag-icon-css styles need to be applied but they are not picked up because of the shadow DOM. Shouldn't a combo box item be "slot" as in ListBox? For ListBox items it works fine to display the flag icons.

I have opened a question on stackoverflow recently, see https://stackoverflow.com/questions/55170886 for details.

**Comment by web-padawan** [comment] 2020-02-18 12:58
A correct way to handle this would be to create a `dom-module` like this:

```html
<dom-module id="my-item-css" theme-for="vaadin-combo-box-item">
  <template>
    <style>
    /* styles from flag-icons.css */
    </style>
  </template>
</dom-module>
```

Using `@import` is not guaranteed to work and is not recommended.

There is no easy fix for the issue, and it's not specific to `vaadin-combo-box` component.
We should document limitations of shadow DOM & external CSS in the new docs site.

Otherwise there is nothing for us to do here. So let me close this as it's not a bug.

**Closed by web-padawan** 2020-02-18 12:58 UTC

**Comment by steffen-harbich-itc** [comment] 2020-02-18 13:27
I would still expect that combo box items shouldn't be placed within the shadow DOM but in separate slots.

**Comment by web-padawan** [comment] 2020-02-18 13:34
> combo box items shouldn't be placed within the shadow DOM but in separate slots.

We can consider this as a potential breaking change in the next major release. 

Exposing the items needs to be done in a way that they work with the virtual scroller component (which will be definitely changed from `iron-list` to something else - has to be decided).
