### ISSUE TITLE
Focus-ring isn't restored back to the element when it's closed

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-combo-box#608] opened 2018-01-31 09:56 UTC
Even though [this](https://github.com/vaadin/vaadin-combo-box/pull/599) PR fixed the issue originally, the problem somehow is still there in the latest revision

**Comment by web-padawan** [comment] 2018-01-31 09:59
This is caused by the polymer/polymer#5067, see my comment [here](https://github.com/Polymer/polymer/issues/5067#issuecomment-361001424)

When observer runs the second time, overlay is already opening and `focus-ring` attribute removed, which overrides `_openedWithFocusRing ` flag back to `false`.

Waiting for Polymer 2.4.1 with the fix, should be quite soon because of a bunch of hotfixes.

**Comment by web-padawan** [comment] 2018-02-07 19:07
Closing per above comment. The beta works fine, not yet deployed the demos but you can check [here](https://web-padawan.github.io/elements-viewer/?vaadin-combo-box#demo).

**Closed by web-padawan** 2018-02-07 19:07 UTC
