### ISSUE TITLE
Do not use fullscreen mode for iPad

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-combo-box#38] opened 2015-11-02 13:01 UTC
Currently on iPad you get this:

![screen shot 2015-11-02 at 10 04 51](https://cloud.githubusercontent.com/assets/161853/10882315/08cee872-816a-11e5-9ea8-d2e4bd503d24.png)

**Comment by jounik** [comment] 2015-11-16 13:52
Duplicate of #32

**Closed** 2015-11-16 13:53 UTC
